wandb_version: 1

^_ignored:
  desc: null
  value: '[]'
^bsuite_id:
  desc: null
  value: catch/1
^logging_mode:
  desc: null
  value: buddy
^num_episodes:
  desc: null
  value: None
^overwrite:
  desc: null
  value: 'True'
^save_path:
  desc: null
  value: /tmp/bsuite
^verbose:
  desc: null
  value: 'True'
_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      4: 3.8.5
      5: 0.10.32
      8:
      - 6
